//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Script : IScriptRunner
{
	public virtual List<ScriptFile> Contents
	{
		get;
		set;
	}

	public virtual void Run()
	{
		throw new System.NotImplementedException();
	}

}

